#define BUILD_BLT_TCL_PROCS 1
#include <bltInt.h>

extern BltTclIntProcs bltTclIntProcs;
/* !BEGIN!: Do not edit below this line. */

static BltTclStubHooks bltTclStubHooks = {
    &bltTclIntProcs
};

BltTclProcs bltTclProcs = {
    TCL_STUB_MAGIC,
    &bltTclStubHooks,
    NULL, /* 0 */
    Blt_AllocInit, /* 1 */
    Blt_Chain_Init, /* 2 */
    Blt_Chain_Create, /* 3 */
    Blt_Chain_Destroy, /* 4 */
    Blt_Chain_NewLink, /* 5 */
    Blt_Chain_AllocLink, /* 6 */
    Blt_Chain_Append, /* 7 */
    Blt_Chain_Prepend, /* 8 */
    Blt_Chain_Reset, /* 9 */
    Blt_Chain_InitLink, /* 10 */
    Blt_Chain_LinkAfter, /* 11 */
    Blt_Chain_LinkBefore, /* 12 */
    Blt_Chain_UnlinkLink, /* 13 */
    Blt_Chain_DeleteLink, /* 14 */
    Blt_Chain_GetNthLink, /* 15 */
    Blt_Chain_Sort, /* 16 */
    Blt_Chain_IsBefore, /* 17 */
    Blt_List_Init, /* 18 */
    Blt_List_Reset, /* 19 */
    Blt_List_Create, /* 20 */
    Blt_List_Destroy, /* 21 */
    Blt_List_CreateNode, /* 22 */
    Blt_List_DeleteNode, /* 23 */
    Blt_List_Append, /* 24 */
    Blt_List_Prepend, /* 25 */
    Blt_List_LinkAfter, /* 26 */
    Blt_List_LinkBefore, /* 27 */
    Blt_List_UnlinkNode, /* 28 */
    Blt_List_GetNode, /* 29 */
    Blt_List_DeleteNodeByKey, /* 30 */
    Blt_List_GetNthNode, /* 31 */
    Blt_List_Sort, /* 32 */
    blt_table_release_tags, /* 33 */
    blt_table_new_tags, /* 34 */
    blt_table_exists, /* 35 */
    blt_table_create, /* 36 */
    blt_table_open, /* 37 */
    blt_table_close, /* 38 */
    blt_table_same_object, /* 39 */
    blt_table_row_get_label_table, /* 40 */
    blt_table_column_get_label_table, /* 41 */
    blt_table_get_row, /* 42 */
    blt_table_get_column, /* 43 */
    blt_table_get_row_by_label, /* 44 */
    blt_table_get_column_by_label, /* 45 */
    blt_table_get_row_by_index, /* 46 */
    blt_table_get_column_by_index, /* 47 */
    blt_table_set_row_label, /* 48 */
    blt_table_set_column_label, /* 49 */
    blt_table_name_to_column_type, /* 50 */
    blt_table_set_column_type, /* 51 */
    blt_table_column_type_to_name, /* 52 */
    blt_table_set_column_tag, /* 53 */
    blt_table_set_row_tag, /* 54 */
    blt_table_create_row, /* 55 */
    blt_table_create_column, /* 56 */
    blt_table_extend_rows, /* 57 */
    blt_table_extend_columns, /* 58 */
    blt_table_delete_row, /* 59 */
    blt_table_delete_column, /* 60 */
    blt_table_move_row, /* 61 */
    blt_table_move_column, /* 62 */
    blt_table_get_obj, /* 63 */
    blt_table_set_obj, /* 64 */
    blt_table_get_string, /* 65 */
    blt_table_set_string, /* 66 */
    blt_table_append_string, /* 67 */
    blt_table_get_double, /* 68 */
    blt_table_set_double, /* 69 */
    blt_table_get_long, /* 70 */
    blt_table_set_long, /* 71 */
    blt_table_get_value, /* 72 */
    blt_table_set_value, /* 73 */
    blt_table_unset_value, /* 74 */
    blt_table_value_exists, /* 75 */
    blt_table_get_row_tag_table, /* 76 */
    blt_table_get_column_tag_table, /* 77 */
    blt_table_row_tags, /* 78 */
    blt_table_column_tags, /* 79 */
    blt_table_tags_are_shared, /* 80 */
    blt_table_row_has_tag, /* 81 */
    blt_table_column_has_tag, /* 82 */
    blt_table_forget_row_tag, /* 83 */
    blt_table_forget_column_tag, /* 84 */
    blt_table_unset_row_tag, /* 85 */
    blt_table_unset_column_tag, /* 86 */
    blt_table_first_row_tag, /* 87 */
    blt_table_first_column_tag, /* 88 */
    blt_table_first_column, /* 89 */
    blt_table_next_column, /* 90 */
    blt_table_first_row, /* 91 */
    blt_table_next_row, /* 92 */
    blt_table_row_spec, /* 93 */
    blt_table_column_spec, /* 94 */
    blt_table_iterate_row, /* 95 */
    blt_table_iterate_column, /* 96 */
    blt_table_iterate_row_objv, /* 97 */
    blt_table_iterate_column_objv, /* 98 */
    blt_table_free_iterator_objv, /* 99 */
    blt_table_iterate_all_rows, /* 100 */
    blt_table_iterate_all_columns, /* 101 */
    blt_table_first_tagged_row, /* 102 */
    blt_table_first_tagged_column, /* 103 */
    blt_table_next_tagged_row, /* 104 */
    blt_table_next_tagged_column, /* 105 */
    blt_table_list_rows, /* 106 */
    blt_table_list_columns, /* 107 */
    blt_table_clear_row_tags, /* 108 */
    blt_table_clear_column_tags, /* 109 */
    blt_table_clear_row_traces, /* 110 */
    blt_table_clear_column_traces, /* 111 */
    blt_table_create_trace, /* 112 */
    blt_table_trace_column, /* 113 */
    blt_table_trace_row, /* 114 */
    blt_table_create_column_trace, /* 115 */
    blt_table_create_column_tag_trace, /* 116 */
    blt_table_create_row_trace, /* 117 */
    blt_table_create_row_tag_trace, /* 118 */
    blt_table_delete_trace, /* 119 */
    blt_table_create_notifier, /* 120 */
    blt_table_create_row_notifier, /* 121 */
    blt_table_create_row_tag_notifier, /* 122 */
    blt_table_create_column_notifier, /* 123 */
    blt_table_create_column_tag_notifier, /* 124 */
    blt_table_delete_notifier, /* 125 */
    blt_table_sort_init, /* 126 */
    blt_table_sort_rows, /* 127 */
    blt_table_sort_rows_subset, /* 128 */
    blt_table_sort_finish, /* 129 */
    blt_table_get_compare_proc, /* 130 */
    blt_table_get_row_map, /* 131 */
    blt_table_get_column_map, /* 132 */
    blt_table_set_row_map, /* 133 */
    blt_table_set_column_map, /* 134 */
    blt_table_restore, /* 135 */
    blt_table_file_restore, /* 136 */
    blt_table_register_format, /* 137 */
    blt_table_unset_keys, /* 138 */
    blt_table_get_keys, /* 139 */
    blt_table_set_keys, /* 140 */
    blt_table_key_lookup, /* 141 */
    blt_table_get_column_limits, /* 142 */
    Blt_Pool_Create, /* 143 */
    Blt_Pool_Destroy, /* 144 */
    Blt_Tree_GetKey, /* 145 */
    Blt_Tree_GetKeyFromNode, /* 146 */
    Blt_Tree_GetKeyFromInterp, /* 147 */
    Blt_Tree_CreateNode, /* 148 */
    Blt_Tree_CreateNodeWithId, /* 149 */
    Blt_Tree_DeleteNode, /* 150 */
    Blt_Tree_MoveNode, /* 151 */
    Blt_Tree_GetNode, /* 152 */
    Blt_Tree_FindChild, /* 153 */
    Blt_Tree_NextNode, /* 154 */
    Blt_Tree_PrevNode, /* 155 */
    Blt_Tree_FirstChild, /* 156 */
    Blt_Tree_LastChild, /* 157 */
    Blt_Tree_IsBefore, /* 158 */
    Blt_Tree_IsAncestor, /* 159 */
    Blt_Tree_PrivateValue, /* 160 */
    Blt_Tree_PublicValue, /* 161 */
    Blt_Tree_GetValue, /* 162 */
    Blt_Tree_ValueExists, /* 163 */
    Blt_Tree_SetValue, /* 164 */
    Blt_Tree_UnsetValue, /* 165 */
    Blt_Tree_AppendValue, /* 166 */
    Blt_Tree_ListAppendValue, /* 167 */
    Blt_Tree_GetArrayValue, /* 168 */
    Blt_Tree_SetArrayValue, /* 169 */
    Blt_Tree_UnsetArrayValue, /* 170 */
    Blt_Tree_AppendArrayValue, /* 171 */
    Blt_Tree_ListAppendArrayValue, /* 172 */
    Blt_Tree_ArrayValueExists, /* 173 */
    Blt_Tree_ArrayNames, /* 174 */
    Blt_Tree_GetValueByKey, /* 175 */
    Blt_Tree_SetValueByKey, /* 176 */
    Blt_Tree_UnsetValueByKey, /* 177 */
    Blt_Tree_AppendValueByKey, /* 178 */
    Blt_Tree_ListAppendValueByKey, /* 179 */
    Blt_Tree_ValueExistsByKey, /* 180 */
    Blt_Tree_FirstKey, /* 181 */
    Blt_Tree_NextKey, /* 182 */
    Blt_Tree_Apply, /* 183 */
    Blt_Tree_ApplyDFS, /* 184 */
    Blt_Tree_ApplyBFS, /* 185 */
    Blt_Tree_SortNode, /* 186 */
    Blt_Tree_Exists, /* 187 */
    Blt_Tree_Open, /* 188 */
    Blt_Tree_Close, /* 189 */
    Blt_Tree_Attach, /* 190 */
    Blt_Tree_GetFromObj, /* 191 */
    Blt_Tree_Size, /* 192 */
    Blt_Tree_CreateTrace, /* 193 */
    Blt_Tree_DeleteTrace, /* 194 */
    Blt_Tree_CreateEventHandler, /* 195 */
    Blt_Tree_DeleteEventHandler, /* 196 */
    Blt_Tree_RelabelNode, /* 197 */
    Blt_Tree_RelabelNodeWithoutNotify, /* 198 */
    Blt_Tree_NodeIdAscii, /* 199 */
    Blt_Tree_NodePath, /* 200 */
    Blt_Tree_NodeRelativePath, /* 201 */
    Blt_Tree_NodePosition, /* 202 */
    Blt_Tree_ClearTags, /* 203 */
    Blt_Tree_HasTag, /* 204 */
    Blt_Tree_AddTag, /* 205 */
    Blt_Tree_RemoveTag, /* 206 */
    Blt_Tree_ForgetTag, /* 207 */
    Blt_Tree_TagHashTable, /* 208 */
    Blt_Tree_TagTableIsShared, /* 209 */
    Blt_Tree_NewTagTable, /* 210 */
    Blt_Tree_FirstTag, /* 211 */
    Blt_Tree_DumpNode, /* 212 */
    Blt_Tree_Dump, /* 213 */
    Blt_Tree_DumpToFile, /* 214 */
    Blt_Tree_Restore, /* 215 */
    Blt_Tree_RestoreFromFile, /* 216 */
    Blt_Tree_Depth, /* 217 */
    Blt_Tree_RegisterFormat, /* 218 */
    Blt_Tree_RememberTag, /* 219 */
    Blt_InitHashTable, /* 220 */
    Blt_InitHashTableWithPool, /* 221 */
    Blt_DeleteHashTable, /* 222 */
    Blt_DeleteHashEntry, /* 223 */
    Blt_FirstHashEntry, /* 224 */
    Blt_NextHashEntry, /* 225 */
    Blt_HashStats, /* 226 */
    Blt_VecMin, /* 227 */
    Blt_VecMax, /* 228 */
    Blt_AllocVectorId, /* 229 */
    Blt_SetVectorChangedProc, /* 230 */
    Blt_FreeVectorId, /* 231 */
    Blt_GetVectorById, /* 232 */
    Blt_NameOfVectorId, /* 233 */
    Blt_NameOfVector, /* 234 */
    Blt_VectorNotifyPending, /* 235 */
    Blt_CreateVector, /* 236 */
    Blt_CreateVector2, /* 237 */
    Blt_GetVector, /* 238 */
    Blt_GetVectorFromObj, /* 239 */
    Blt_VectorExists, /* 240 */
    Blt_ResetVector, /* 241 */
    Blt_ResizeVector, /* 242 */
    Blt_DeleteVectorByName, /* 243 */
    Blt_DeleteVector, /* 244 */
    Blt_ExprVector, /* 245 */
    Blt_InstallIndexProc, /* 246 */
    Blt_VectorExists2, /* 247 */
};

/* !END!: Do not edit above this line. */
