/* -*- mode: c; c-basic-offset: 4; indent-tabs-mode: nil -*- */
#define BUILD_BLT_TK_PROCS 1
#include <bltInt.h>

/* !BEGIN!: Do not edit below this line. */

BltTkIntProcs bltTkIntProcs = {
    TCL_STUB_MAGIC,
    NULL,
    NULL, /* 0 */
    Blt_Draw3DRectangle, /* 1 */
    Blt_Fill3DRectangle, /* 2 */
    Blt_AdjustViewport, /* 3 */
    Blt_GetScrollInfoFromObj, /* 4 */
    Blt_UpdateScrollbar, /* 5 */
    Blt_FreeColorPair, /* 6 */
    Blt_LineRectClip, /* 7 */
    Blt_GetPrivateGC, /* 8 */
    Blt_GetPrivateGCFromDrawable, /* 9 */
    Blt_FreePrivateGC, /* 10 */
    Blt_GetWindowFromObj, /* 11 */
    Blt_GetParentWindow, /* 12 */
    Blt_FindChild, /* 13 */
    Blt_FirstChild, /* 14 */
    Blt_NextChild, /* 15 */
    Blt_RelinkWindow, /* 16 */
    Blt_Toplevel, /* 17 */
    Blt_GetPixels, /* 18 */
    Blt_NameOfFill, /* 19 */
    Blt_NameOfResize, /* 20 */
    Blt_GetXY, /* 21 */
    Blt_GetProjection, /* 22 */
    Blt_DrawArrowOld, /* 23 */
    Blt_DrawArrow, /* 24 */
    Blt_MakeTransparentWindowExist, /* 25 */
    Blt_TranslateAnchor, /* 26 */
    Blt_AnchorPoint, /* 27 */
    Blt_MaxRequestSize, /* 28 */
    Blt_GetWindowId, /* 29 */
    Blt_InitXRandrConfig, /* 30 */
    Blt_SizeOfScreen, /* 31 */
    Blt_RootX, /* 32 */
    Blt_RootY, /* 33 */
    Blt_RootCoordinates, /* 34 */
    Blt_MapToplevelWindow, /* 35 */
    Blt_UnmapToplevelWindow, /* 36 */
    Blt_RaiseToplevelWindow, /* 37 */
    Blt_LowerToplevelWindow, /* 38 */
    Blt_ResizeToplevelWindow, /* 39 */
    Blt_MoveToplevelWindow, /* 40 */
    Blt_MoveResizeToplevelWindow, /* 41 */
    Blt_GetWindowRegion, /* 42 */
    Blt_GetWindowInstanceData, /* 43 */
    Blt_SetWindowInstanceData, /* 44 */
    Blt_DeleteWindowInstanceData, /* 45 */
    Blt_ReparentWindow, /* 46 */
    Blt_GetDrawableAttribs, /* 47 */
    Blt_SetDrawableAttribs, /* 48 */
    Blt_SetDrawableAttribsFromWindow, /* 49 */
    Blt_FreeDrawableAttribs, /* 50 */
    Blt_GetBitmapGC, /* 51 */
    Blt_GetPixmapAbortOnError, /* 52 */
    Blt_ScreenDPI, /* 53 */
    Blt_OldConfigModified, /* 54 */
    Blt_GetLineExtents, /* 55 */
    Blt_GetBoundingBox, /* 56 */
    Blt_GetFont, /* 57 */
    Blt_AllocFontFromObj, /* 58 */
    Blt_DrawWithEllipsis, /* 59 */
    Blt_GetFontFromObj, /* 60 */
    Blt_Font_GetMetrics, /* 61 */
    Blt_TextWidth, /* 62 */
    Blt_Font_GetInterp, /* 63 */
    Blt_Font_GetFile, /* 64 */
    Blt_GetBg, /* 65 */
    Blt_GetBgFromObj, /* 66 */
    Blt_Bg_BorderColor, /* 67 */
    Blt_Bg_Border, /* 68 */
    Blt_Bg_PaintBrush, /* 69 */
    Blt_Bg_Name, /* 70 */
    Blt_FreeBg, /* 71 */
    Blt_Bg_DrawRectangle, /* 72 */
    Blt_Bg_FillRectangle, /* 73 */
    Blt_Bg_DrawPolygon, /* 74 */
    Blt_Bg_FillPolygon, /* 75 */
    Blt_Bg_GetOrigin, /* 76 */
    Blt_Bg_SetChangedProc, /* 77 */
    Blt_Bg_SetOrigin, /* 78 */
    Blt_Bg_DrawFocus, /* 79 */
    Blt_Bg_BorderGC, /* 80 */
    Blt_Bg_SetFromBackground, /* 81 */
    Blt_Bg_UnsetClipRegion, /* 82 */
    Blt_Bg_SetClipRegion, /* 83 */
    Blt_DestroyBindingTable, /* 84 */
    Blt_CreateBindingTable, /* 85 */
    Blt_ConfigureBindings, /* 86 */
    Blt_ConfigureBindingsFromObj, /* 87 */
    Blt_PickCurrentItem, /* 88 */
    Blt_DeleteBindings, /* 89 */
    Blt_MoveBindingTable, /* 90 */
    Blt_Afm_SetPrinting, /* 91 */
    Blt_Afm_IsPrinting, /* 92 */
    Blt_Afm_TextWidth, /* 93 */
    Blt_Afm_GetMetrics, /* 94 */
    Blt_Afm_GetPostscriptFamily, /* 95 */
    Blt_Afm_GetPostscriptName, /* 96 */
    Blt_SetDashes, /* 97 */
    Blt_ResetLimits, /* 98 */
    Blt_GetLimitsFromObj, /* 99 */
    Blt_ConfigureInfoFromObj, /* 100 */
    Blt_ConfigureValueFromObj, /* 101 */
    Blt_ConfigureWidgetFromObj, /* 102 */
    Blt_ConfigureComponentFromObj, /* 103 */
    Blt_ConfigModified, /* 104 */
    Blt_NameOfState, /* 105 */
    Blt_FreeOptions, /* 106 */
    Blt_ObjIsOption, /* 107 */
    Blt_GetPixelsFromObj, /* 108 */
    Blt_GetPadFromObj, /* 109 */
    Blt_GetStateFromObj, /* 110 */
    Blt_GetFillFromObj, /* 111 */
    Blt_GetResizeFromObj, /* 112 */
    Blt_GetDashesFromObj, /* 113 */
    Blt_Image_IsDeleted, /* 114 */
    Blt_Image_GetMaster, /* 115 */
    Blt_Image_GetType, /* 116 */
    Blt_Image_GetInstanceData, /* 117 */
    Blt_Image_Name, /* 118 */
    Blt_Image_NameOfType, /* 119 */
    Blt_FreePainter, /* 120 */
    Blt_GetPainter, /* 121 */
    Blt_GetPainterFromDrawable, /* 122 */
    Blt_PainterGC, /* 123 */
    Blt_PainterDepth, /* 124 */
    Blt_PaintPicture, /* 125 */
    Blt_PaintPictureWithBlend, /* 126 */
    Blt_PaintCheckbox, /* 127 */
    Blt_PaintRadioButton, /* 128 */
    Blt_PaintRadioButtonOld, /* 129 */
    Blt_PaintDelete, /* 130 */
    Blt_Ps_Create, /* 131 */
    Blt_Ps_Free, /* 132 */
    Blt_Ps_GetValue, /* 133 */
    Blt_Ps_GetDBuffer, /* 134 */
    Blt_Ps_GetInterp, /* 135 */
    Blt_Ps_GetScratchBuffer, /* 136 */
    Blt_Ps_SetInterp, /* 137 */
    Blt_Ps_Append, /* 138 */
    Blt_Ps_AppendBytes, /* 139 */
    Blt_Ps_VarAppend, /* 140 */
    Blt_Ps_Format, /* 141 */
    Blt_Ps_SetClearBackground, /* 142 */
    Blt_Ps_IncludeFile, /* 143 */
    Blt_Ps_GetPicaFromObj, /* 144 */
    Blt_Ps_GetPadFromObj, /* 145 */
    Blt_Ps_ComputeBoundingBox, /* 146 */
    Blt_Ps_DrawPicture, /* 147 */
    Blt_Ps_Rectangle, /* 148 */
    Blt_Ps_SaveFile, /* 149 */
    Blt_Ps_XSetLineWidth, /* 150 */
    Blt_Ps_XSetBackground, /* 151 */
    Blt_Ps_XSetBitmapData, /* 152 */
    Blt_Ps_XSetForeground, /* 153 */
    Blt_Ps_XSetFont, /* 154 */
    Blt_Ps_XSetDashes, /* 155 */
    Blt_Ps_XSetLineAttributes, /* 156 */
    Blt_Ps_XSetStipple, /* 157 */
    Blt_Ps_Polyline, /* 158 */
    Blt_Ps_XDrawLines, /* 159 */
    Blt_Ps_XDrawSegments, /* 160 */
    Blt_Ps_DrawPolyline, /* 161 */
    Blt_Ps_DrawSegments2d, /* 162 */
    Blt_Ps_Draw3DRectangle, /* 163 */
    Blt_Ps_Fill3DRectangle, /* 164 */
    Blt_Ps_XFillRectangle, /* 165 */
    Blt_Ps_XFillRectangles, /* 166 */
    Blt_Ps_XFillPolygon, /* 167 */
    Blt_Ps_DrawPhoto, /* 168 */
    Blt_Ps_XDrawWindow, /* 169 */
    Blt_Ps_DrawText, /* 170 */
    Blt_Ps_DrawBitmap, /* 171 */
    Blt_Ps_XSetCapStyle, /* 172 */
    Blt_Ps_XSetJoinStyle, /* 173 */
    Blt_Ps_PolylineFromXPoints, /* 174 */
    Blt_Ps_Polygon, /* 175 */
    Blt_Ps_SetPrinting, /* 176 */
    Blt_Ts_CreateLayout, /* 177 */
    Blt_Ts_TitleLayout, /* 178 */
    Blt_Ts_DrawLayout, /* 179 */
    Blt_Ts_GetExtents, /* 180 */
    Blt_Ts_ResetStyle, /* 181 */
    Blt_Ts_FreeStyle, /* 182 */
    Blt_Ts_SetDrawStyle, /* 183 */
    Blt_DrawText, /* 184 */
    Blt_DrawText2, /* 185 */
    Blt_Ts_Bitmap, /* 186 */
    Blt_DrawTextWithRotatedFont, /* 187 */
    Blt_DrawLayout, /* 188 */
    Blt_GetTextExtents, /* 189 */
    Blt_RotateStartingTextPositions, /* 190 */
    Blt_ComputeTextLayout, /* 191 */
    Blt_DrawTextLayout, /* 192 */
    Blt_CharBbox, /* 193 */
    Blt_UnderlineTextLayout, /* 194 */
    Blt_Ts_UnderlineLayout, /* 195 */
    Blt_Ts_DrawText, /* 196 */
    Blt_MeasureText, /* 197 */
    Blt_FreeTextLayout, /* 198 */
};

/* !END!: Do not edit above this line. */
